[build]
  base = '.'
  publish = 'dist/ssr/client'
  command = 'quasar build -m ssr'

[functions]
  external_node_modules = ["express"]
  directory = 'dist/ssr/netlify/functions'

[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/index/:splat"

[dev]
  command = "quasar build -m ssr"
  port = 8888
  targetPort = 3000
  publish = "dist/ssr"
  autoLaunch = true
  framework = "#custom"

